name: Deploy to Raspberry Pi

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
          
      - name: Install dependencies
        run: npm install
        
      - name: Set up environment variables
        run: |
          echo "EMAIL_USER=\"${{ secrets.EMAIL_USER }}\"" >> .env
          echo "EMAIL_KEY=\"${{ secrets.EMAIL_KEY }}\"" >> .env
          echo "EMAIL_TO=\"${{ secrets.EMAIL_TO }}\"" >> .env
          
      - name: Copy files
        run: |
          cp -r ~/actions-runner/_work/petfinder-scraper/petfinder-scraper ~/petfinder-scraper
