name: Deploy to Raspberry Pi

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm i
